force-app/main/default/objects/Account/fields/sugati__A_Email__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Email__c</fullName>
    <inlineHelpText>Account Email is required</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_First_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_First_Name__c</fullName>
    <description>First name (Eg: Tim, Donna)</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Status__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Status__c</fullName>
    <formula>IF(AND(sugati__A_Total_Bookings__c = 0,sugati__A_Total_Quotes__c = 0), &quot;Lead&quot;, 
IF(AND(sugati__A_Total_Bookings__c = 0,sugati__A_Total_Quotes__c &gt; 0), &quot;Potential Client&quot;,
IF(sugati__A_Total_Bookings__c = 1, &quot;Client&quot;, 
IF(sugati__A_Total_Bookings__c &gt; 1, &quot;Repeat Client&quot;, null
))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Total_Bookings__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Total_Bookings__c</fullName>
    <label>Total Bookings</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Booked, Booking cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>sugati__Total_Revenue__c</fullName>
    <label>Total Revenue</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Booked</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Country__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Nights__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Nights__c</fullName>
    <label>Nights</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_No_of_Nights__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_No_of_Nights__c</fullName>
    <formula>sugati__O_Return_Date__c -  sugati__O_Departure_Date__c</formula>
    <label>No of Nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SugatiAccountPageCtrl.cls
public with sharing class SugatiAccountPageCtrl {

    @AuraEnabled(cacheable=true)
    public static Account getAccount(Id accountId) {
        return [
            SELECT Id, sugati__A_First_Name__c, sugati__A_Last_Name__c,
                   sugati__A_Email__c, Phone, // BillingAddress address type
                   BillingCity, BillingCountry,
                   Description,
                   Rating,
                   Active__c,
                   sugati__A_Status__c,
                   sugati__Total_Revenue__c,
                   sugati__A_Total_Bookings__c,
                   CurrencyIsoCode
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getOpportunities(Id accountId) {
        return [
            SELECT Id, Name, StageName,
                   Amount, CloseDate,
                   Probability,
                   sugati__O_Booking_Date__c,
                   sugati__O_Nights__c,
                   sugati__O_No_of_Nights__c,
                   sugati__O_Country__c
            FROM Opportunity
            WHERE AccountId = :accountId
            ORDER BY sugati__O_Booking_Date__c DESC NULLS LAST
        ];
    }
}