force-app/main/default/objects/Account/fields/sugati__A_Email__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Email__c</fullName>
    <inlineHelpText>Account Email is required</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_First_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_First_Name__c</fullName>
    <description>First name (Eg: Tim, Donna)</description>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Last_Enquiry_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Last_Enquiry_Date__c</fullName>
    <label>Last Enquiry Date</label>
    <summarizedField>Opportunity.CloseDate</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>notEqual</operation>
        <value>Booked, Booking Optional, Booking cancelled, Training enquiry</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Status__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Status__c</fullName>
    <formula>IF(AND(sugati__A_Total_Bookings__c = 0,sugati__A_Total_Quotes__c = 0), &quot;Lead&quot;, 
IF(AND(sugati__A_Total_Bookings__c = 0,sugati__A_Total_Quotes__c &gt; 0), &quot;Potential Client&quot;,
IF(sugati__A_Total_Bookings__c = 1, &quot;Client&quot;, 
IF(sugati__A_Total_Bookings__c &gt; 1, &quot;Repeat Client&quot;, null
))))</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__A_Total_Bookings__c.field-meta.xml
<CustomField>
    <fullName>sugati__A_Total_Bookings__c</fullName>
    <label>Total Bookings</label>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Booked, Booking cancelled</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/sugati__Total_Revenue__c.field-meta.xml
<CustomField>
    <fullName>sugati__Total_Revenue__c</fullName>
    <label>Total Revenue</label>
    <summarizedField>Opportunity.Amount</summarizedField>
    <summaryFilterItems>
        <field>Opportunity.StageName</field>
        <operation>equals</operation>
        <value>Booked</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Activity/fields/sugati__Type__c.field-meta.xml
<CustomField>
    <fullName>sugati__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enquiry</fullName>
            </value>
            <value>
                <fullName>Quote pending</fullName>
            </value>
            <value>
                <fullName>Quoted to client</fullName>
            </value>
            <value>
                <fullName>Quote gone cold</fullName>
            </value>
            <value>
                <fullName>Booking Optional</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Booking cancelled</fullName>
            </value>
            <value>
                <fullName>Training enquiry</fullName>
            </value>
            <value>
                <fullName>Redundant</fullName>
            </value>
            <value>
                <fullName>Enquiry gone cold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/sugati__C_Age__c.field-meta.xml
<CustomField>
    <fullName>sugati__C_Age__c</fullName>
    <formula>IF( NOT( ISBLANK( Birthdate ) ) ,
  IF( DATE( 2000 , MONTH( Birthdate ) , DAY( Birthdate ) ) &lt;= DATE( 2000 , MONTH( TODAY() ) , DAY( TODAY() ) ),
     YEAR (Today()) - YEAR ( Birthdate ),
     YEAR (Today()) - YEAR ( Birthdate ) -1 ),
  sugati__C_Age_In_Years__c)</formula>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/sugati__C_Expires_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__C_Expires_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/sugati__C_Lead_Passenger__c.field-meta.xml
<CustomField>
    <fullName>sugati__C_Lead_Passenger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Passenger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/sugati__C_Nationality__c.field-meta.xml
<CustomField>
    <fullName>sugati__C_Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>Bruneian</fullName>
            </value>
            <value>
                <fullName>Bulgarian</fullName>
            </value>
            <value>
                <fullName>Burkinabe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/sugati__C_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>sugati__C_Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/sugati__Occupancy_Type__c.field-meta.xml
<CustomField>
    <fullName>sugati__Occupancy_Type__c</fullName>
    <label>Occupancy Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adult</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
            <value>
                <fullName>Infant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Country__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Nights__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Nights__c</fullName>
    <label>Nights</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_No_of_Nights__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_No_of_Nights__c</fullName>
    <formula>sugati__O_Return_Date__c -  sugati__O_Departure_Date__c</formula>
    <label>No of Nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/sugati__O_Status__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Built</fullName>
            </value>
            <value>
                <fullName>On Sale</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Guaranteed</fullName>
            </value>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Sold Out</fullName>
            </value>
            <value>
                <fullName>Departed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>On Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sugati__Country__c/sugati__Country__c.object-meta.xml
<CustomObject>
    <description>Store a list of Countries</description>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Country__c/fields/sugati__C_Continent__c.field-meta.xml
<CustomField>
    <fullName>sugati__C_Continent__c</fullName>
    <inlineHelpText>Which region is the country in?</inlineHelpText>
    <label>Continent</label>
    <referenceTo>sugati__Continent__c</referenceTo>
    <relationshipLabel>Countries</relationshipLabel>
    <relationshipName>Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/sugati__Supplier_Booking__c.object-meta.xml
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplier Booking</relationshipLabel>
    <relationshipName>Supplier_Booking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Supplier_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Supplier_Name__c</fullName>
    <formula>sugati__SB_Supplier__r.Name</formula>
    <label>Supplier Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Travelling_Country__c/sugati__Travelling_Country__c.object-meta.xml
<CustomObject>
    <label>Travelling Country</label>
    <nameField>
        <displayFormat>TC-{0000000000}</displayFormat>
        <label>Travelling Country ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travelling Countries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Travelling_Country__c/fields/sugati__TC_Country__c.field-meta.xml
<CustomField>
    <fullName>sugati__TC_Country__c</fullName>
    <label>Country</label>
    <referenceTo>sugati__Country__c</referenceTo>
    <relationshipLabel>Travelling Countries</relationshipLabel>
    <relationshipName>Travelling_Countries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sugati__Travelling_Country__c/fields/sugati__TC_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sugati__TC_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Travelling Countries</relationshipLabel>
    <relationshipName>Travelling_Countries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SugatiTravellerPageCtrl.cls
public with sharing class SugatiTravellerPageCtrl {

    // ---- PUBLIC METHODS ----

    /**
     * Retrieves a single Account record by Id for display on the traveller page.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account record to retrieve
     * @return           : Account record with all required display fields
     */
    @AuraEnabled(cacheable=true)
    public static Account getAccount(Id accountId) {
        // if (!Utility.canAccessObj('Account')) {
        //     throw new AuraHandledException('Insufficient access to Account records.');
        // }
        return [
            SELECT Id,
                   sugati__A_First_Name__c,
                   sugati__A_Last_Name__c,
                   sugati__A_Email__c,
                   Phone,
                   BillingCity,
                   BillingCountry,
                   Description,
                   Rating,
                   Active__c,
                   sugati__A_Status__c,
                   sugati__Total_Revenue__c,
                   sugati__A_Total_Bookings__c,
                   CurrencyIsoCode,
                   sugati__A_Last_Enquiry_Date__c
            FROM Account
            WHERE Id = :accountId
            LIMIT 1
        ];
    }

    /**
     * Retrieves Opportunity records linked to a given Account for display
     * on the traveller page booking history.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose opportunities to retrieve
     * @return           : List of Opportunity records ordered by booking date descending
     */
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getOpportunities(Id accountId) {
        Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);
        return [
            SELECT Id,
                Name,
                StageName,
                Amount,
                CloseDate,
                Probability,
                sugati__O_Booking_Date__c,
                sugati__O_Nights__c,
                sugati__O_No_of_Nights__c,
                sugati__O_Country__c,
                sugati__O_Status__c
            FROM Opportunity
            WHERE AccountId = :accountId
            AND   CloseDate >= :windowStart   // direct field, indexable
            ORDER BY CloseDate DESC NULLS LAST
            LIMIT 1000
        ];
    }

    /**
     * Retrieves Task records linked directly to a given Account
     * for display in the activity timeline.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose tasks to retrieve
     * @return           : List of Task records ordered by activity date descending
     */
    @AuraEnabled(cacheable=true)
    public static List<Task> getTasks(Id accountId) {
        Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);
        return [
            SELECT Id,
                Subject,
                ActivityDate,
                sugati__Type__c,
                Description,
                TaskSubtype
            FROM Task
            WHERE WhatId = :accountId
            AND   ActivityDate >= :windowStart   // direct field, indexable
            ORDER BY ActivityDate DESC NULLS LAST
            LIMIT 1000
        ];
    }

    /**
     * Retrieves Contact records linked to a given Account for display
     * in the traveller passenger details component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose contacts to retrieve
     * @return           : List of Contact records ordered by last name ascending
     */
    @AuraEnabled(cacheable=true)
    public static List<Contact> getContacts(Id accountId) {
        // if (!Utility.canAccessObj('Contact')) {
        //     throw new AuraHandledException('Insufficient access to Contact records.');
        // }
        return [
            SELECT Id,
                   Name,
                   FirstName,
                   LastName,
                   Birthdate,
                   sugati__C_Nationality__c,
                   sugati__C_Passport_Number__c,
                   sugati__C_Expires_Date__c,
                   sugati__C_Age__c,
                   sugati__Occupancy_Type__c,
                   sugati__C_Lead_Passenger__c,
                   LeadSource
            FROM Contact
            WHERE AccountId = :accountId
            ORDER BY LastName ASC NULLS LAST
            LIMIT 1000
        ];
    }

    /**
     * Retrieves Travelling Country records linked to booked Opportunities
     * on a given Account, for use in the destinations map component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose travelling countries to retrieve
     * @return           : List of sugati__Travelling_Country__c records ordered by country name ascending
     */
    @AuraEnabled(cacheable=true)
    public static List<sugati__Travelling_Country__c> getTravellingCountries(Id accountId) {
        // Collect Opportunity Ids first on a direct indexed field,
        // then use IN bind — avoids cross-object filter entirely
        Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);

        Set<Id> oppIds = new Map<Id, Opportunity>([
            SELECT Id
            FROM Opportunity
            WHERE AccountId  = :accountId
            AND   CloseDate >= :windowStart
            LIMIT 1000
        ]).keySet();

        if (oppIds.isEmpty()) {
            return new List<sugati__Travelling_Country__c>();
        }

        return [
            SELECT Id,
                sugati__TC_Country__c,
                sugati__TC_Country__r.sugati__C_Continent__c,
                sugati__TC_Country__r.sugati__C_Continent__r.Name,
                sugati__TC_Opportunity__c
            FROM sugati__Travelling_Country__c
            WHERE sugati__TC_Opportunity__c IN :oppIds   // direct field, indexable
            ORDER BY sugati__TC_Country__c ASC NULLS LAST
            LIMIT 1000
        ];
    }

    /**
     * Retrieves Accommodation Supplier Booking records linked to Opportunities
     * on a given Account, for use in the stays history component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose supplier bookings to retrieve
     * @return           : List of sugati__Supplier_Booking__c records of Accommodation record type
     */
    @AuraEnabled(cacheable=true)
    public static List<sugati__Supplier_Booking__c> getSupplierBookings(Id accountId) {
        Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);

        Set<Id> oppIds = new Map<Id, Opportunity>([
            SELECT Id
            FROM Opportunity
            WHERE AccountId  = :accountId
            AND   CloseDate >= :windowStart
            LIMIT 1000
        ]).keySet();

        if (oppIds.isEmpty()) {
            return new List<sugati__Supplier_Booking__c>();
        }

        return [
            SELECT Id,
                sugati__SB_Supplier_Name__c,
                sugati__SB_Opportunity__c,
                sugati__SB_Opportunity__r.sugati__O_Booking_Date__c,
                RecordType.DeveloperName
            FROM sugati__Supplier_Booking__c
            WHERE sugati__SB_Opportunity__c IN :oppIds       // direct field, indexable
            AND   RecordType.DeveloperName  =  'Accommodation'
            ORDER BY sugati__SB_From_Date__c DESC NULLS LAST // direct field, not cross-object
            LIMIT 1000
        ];
    }

    /**
     * Retrieves Task records linked to Opportunities on a given Account,
     * for use in the opportunity activity timeline component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose opportunity tasks to retrieve
     * @return           : List of Task records ordered by activity date ascending
     */
    @AuraEnabled(cacheable=true)
    public static List<Task> getOpportunityTasks(Id accountId) {
        Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);

        Set<Id> oppIds = new Map<Id, Opportunity>([
            SELECT Id
            FROM Opportunity
            WHERE AccountId  = :accountId
            AND   CloseDate >= :windowStart
            LIMIT 1000
        ]).keySet();

        if (oppIds.isEmpty()) {
            return new List<Task>();
        }

        return [
            SELECT Id,
                Subject,
                ActivityDate,
                WhatId
            FROM Task
            WHERE WhatId          IN :oppIds           // direct field, indexable
            AND   ActivityDate    >= :windowStart
            ORDER BY ActivityDate ASC NULLS LAST
            LIMIT 1000
        ];
    }
    /**
     * Retrieves Credit Memo records linked to a given Account
     * for display in the credit memo summary component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  accountId : Id of the Account whose credit memos to retrieve
     * @return           : List of sugati__Credit_Memo__c records ordered by memo date descending
     */
    @AuraEnabled(cacheable=true)
    public static List<sugati__Credit_Memo__c> getCreditMemos(Id accountId) {
        // if (!Utility.canAccessObj('sugati__Credit_Memo__c')) {
        //     throw new AuraHandledException('Insufficient access to Credit Memo records.');
        // }
        return [
            SELECT Id,
                   Name,
                   sugati__CM_Amount__c,
                   sugati__CM_Credit_Memo_Date__c,
                   sugati__CM_Is_Expired__c,
                   sugati__O_Credit_Expiry_Date_c__c,
                   sugati__CM_Opportunity__c,
                   sugati__CM_Opportunity__r.Name,
                   sugati__CM_Account__c
            FROM sugati__Credit_Memo__c
            WHERE sugati__CM_Account__c = :accountId
            ORDER BY sugati__CM_Credit_Memo_Date__c DESC NULLS LAST
            LIMIT 1000
        ];
    }
}