force-app/main/default/objects/Opportunity/fields/sugati__O_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__O_Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sugati__FAM_Visit__c/sugati__FAM_Visit__c.object-meta.xml
<CustomObject>
    <description>Staff Visits</description>
    <label>FAM Visit</label>
    <nameField>
        <displayFormat>FV-{00000}</displayFormat>
        <label>FAM Visit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FAM Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__FAM_Visit__c/fields/sugati__FV_FAM_Visit_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__FV_FAM_Visit_Start_Date__c</fullName>
    <label>FAM Visit Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sugati__Room_Type__c/sugati__Room_Type__c.object-meta.xml
<CustomObject>
    <description>A list of room types for each accommodation option.</description>
    <label>Room Type</label>
    <nameField>
        <displayFormat>RT-{0000000000}</displayFormat>
        <label>Room Type ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Room Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Room_Type__c/fields/sugati__RT_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__RT_Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/sugati__Supplier__c.object-meta.xml
<CustomObject>
    <label>Supplier</label>
    <nameField>
        <label>Supplier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S1_Country__c.field-meta.xml
<CustomField>
    <fullName>sugati__S1_Country__c</fullName>
    <label>1. Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_City__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Commission__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Commission__c</fullName>
    <label>Commission %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Description__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Emergency_Phone__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Emergency_Phone__c</fullName>
    <label>Emergency Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Parent_Supplier__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Parent_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Supplier</label>
    <referenceTo>sugati__Supplier__c</referenceTo>
    <relationshipLabel>Suppliers (Parent Supplier)</relationshipLabel>
    <relationshipName>Suppliers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Phone__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Rating__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Rating__c</fullName>
    <inlineHelpText>Only For Accommodation</inlineHelpText>
    <label>Rating</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Type__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accommodation</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
            <value>
                <fullName>Agency</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>Boat</fullName>
            </value>
            <value>
                <fullName>Car Hire</fullName>
            </value>
            <value>
                <fullName>Cruise</fullName>
            </value>
            <value>
                <fullName>DMC</fullName>
            </value>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Driver Guide</fullName>
            </value>
            <value>
                <fullName>Flight</fullName>
            </value>
            <value>
                <fullName>Guide</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Taxi</fullName>
            </value>
            <value>
                <fullName>Tourist Board</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Rail</fullName>
            </value>
            <value>
                <fullName>Ship/Cruise Number</fullName>
            </value>
            <value>
                <fullName>Tour Operator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sugati__Supplier__c/fields/sugati__S_Website__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_Website__c</fullName>
    <label>Website</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/sugati__Supplier_Booking__c.object-meta.xml
<CustomObject>
    <description>Booking Options. All elements are stored here because Itinerary options are coming out in itemised way.</description>
    <label>Supplier Booking</label>
    <nameField>
        <displayFormat>SB-{0000000000}</displayFormat>
        <label>Supplier Booking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Booking</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__S_SB_Option_Number__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_SB_Option_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Used when there are multiple options for this date across supplier bookings</description>
    <label>Option Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__S_SB_Total_Gross_Cost_Booking_Currency__c.field-meta.xml
<CustomField>
    <fullName>sugati__S_SB_Total_Gross_Cost_Booking_Currency__c</fullName>
    <description>Sum of all Gross Cost in Booking Currency</description>
    <label>Total Gross Cost (Booking Currency)</label>
    <summarizedField>sugati__Supplier_Cost__c.sugati__S_SC_Gross_Cost_Booking_Currency__c</summarizedField>
    <summaryForeignKey>sugati__Supplier_Cost__c.sugati__SC_Supplier_Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_From_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_From_Date__c</fullName>
    <label>From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Night__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Night__c</fullName>
    <formula>sugati__SB_To_Date__c -  sugati__SB_From_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nights</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Supplier Booking</relationshipLabel>
    <relationshipName>Supplier_Booking</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Pax_for_Costing__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Pax_for_Costing__c</fullName>
    <label>Pax for Costing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Room_Type__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Room_Type__c</fullName>
    <description>The value must come from Room Type Object.</description>
    <label>Room Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Selected_Room_Type__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Selected_Room_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selected Room Type</label>
    <referenceTo>sugati__Room_Type__c</referenceTo>
    <relationshipLabel>Supplier Booking</relationshipLabel>
    <relationshipName>Supplier_Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_Supplier__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>sugati__Supplier__c</referenceTo>
    <relationshipLabel>Supplier Booking</relationshipLabel>
    <relationshipName>Supplier_Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Booking__c/fields/sugati__SB_To_Date__c.field-meta.xml
<CustomField>
    <fullName>sugati__SB_To_Date__c</fullName>
    <label>To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/sugati__Supplier_Contact__c.object-meta.xml
<CustomObject>
    <description>A list of contacts from the suppliers</description>
    <label>Supplier Contact</label>
    <nameField>
        <displayFormat>SC-{0000000000}</displayFormat>
        <label>Supplier Contact ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Supplier Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_Email__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_First_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_Language__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_Phone__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_Supplier__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_Supplier__c</fullName>
    <label>Supplier</label>
    <referenceTo>sugati__Supplier__c</referenceTo>
    <relationshipLabel>Supplier Contacts</relationshipLabel>
    <relationshipName>Supplier_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/sugati__Supplier_Contact__c/fields/sugati__SC_Title__c.field-meta.xml
<CustomField>
    <fullName>sugati__SC_Title__c</fullName>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SugatiSupplierPageCtrl.cls
public with sharing class SugatiSupplierPageCtrl {

    // ---- PUBLIC METHODS ----

    /**
     * Retrieves a single Supplier record by Id for display on the supplier page.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  supplierId : Id of the Supplier record to retrieve
     * @return            : sugati__Supplier__c record with all required display fields
     */
    @AuraEnabled(cacheable=true)
    public static sugati__Supplier__c getSupplier(Id supplierId) {
        // if (!Utility.canAccessObj('sugati__Supplier__c')) {
        //     throw new AuraHandledException('Insufficient access to Supplier records.');
        // }
        return [
            SELECT Id,
                   Name,
                   sugati__S_Type__c,
                   RecordType.DeveloperName,
                   sugati__S_Phone__c,
                   sugati__S_Website__c,
                   sugati__S_Rating__c,
                   sugati__S_City__c,
                   sugati__S1_Country__c,
                   sugati__S_Emergency_Phone__c,
                   sugati__S_Commission__c,
                   sugati__S_Parent_Supplier__c,
                   sugati__S_Description__c,
                   sugati__S_Parent_Supplier__r.Name,
                   CurrencyIsoCode,
                   CreatedDate
            FROM sugati__Supplier__c
            WHERE Id = :supplierId
            LIMIT 1
        ];
    }

    /**
     * Retrieves Supplier Booking records for the current and prior calendar year
     * for a given Supplier. Scoped to sugati__SB_From_Date__c >= 1 Jan last year
     * to keep the query selective on a direct indexed field.
     * Excludes Agency and Agent record types via pre-fetched RecordType Ids.
     * Hard-capped at 2000 rows as a governor safety net.
     * @param  supplierId : Id of the Supplier record whose bookings to retrieve
     * @return            : List of sugati__Supplier_Booking__c records ordered by start date descending
     */
    // @AuraEnabled(cacheable=true)
    // public static List<sugati__Supplier_Booking__c> getSupplierBookings(Id supplierId) {
    //     Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);

    //     // Pre-fetch excluded RecordType Ids — avoids non-indexable cross-object RT filter
    //     Set<Id> excludedRtIds = new Map<Id, RecordType>([
    //         SELECT Id
    //         FROM RecordType
    //         WHERE SObjectType    = 'sugati__Supplier__c'
    //         AND   DeveloperName IN ('Agency', 'Agent')
    //     ]).keySet();

    //     return [
    //         SELECT Id,
    //             sugati__SB_Opportunity__c,
    //             sugati__SB_Opportunity__r.Name,
    //             sugati__SB_Opportunity__r.AccountId,
    //             sugati__SB_Opportunity__r.Account.Name,
    //             sugati__SB_Opportunity__r.sugati__O_Booking_Date__c,
    //             sugati__S_SB_Total_Gross_Cost_Booking_Currency__c,
    //             sugati__SB_Night__c,
    //             sugati__SB_Pax_for_Costing__c,
    //             sugati__S_SB_Option_Number__c,
    //             sugati__SB_Room_Type__c,
    //             sugati__SB_From_Date__c,
    //             sugati__SB_To_Date__c,
    //             CurrencyIsoCode
    //         FROM sugati__Supplier_Booking__c
    //         WHERE sugati__SB_Supplier__c      =  :supplierId
    //         AND   sugati__SB_Opportunity__c   != null
    //         AND   sugati__SB_From_Date__c     >= :windowStart
    //         AND   sugati__SB_Supplier__r.RecordTypeId NOT IN :excludedRtIds
    //         ORDER BY sugati__SB_From_Date__c DESC NULLS LAST
    //         LIMIT 2000
    //     ];
    // }

    @AuraEnabled(cacheable=true)
    public static List<sugati__Supplier_Booking__c> getSupplierBookings(Id supplierId) {
        Date windowStart = Date.newInstance(Date.today().year() - 1, 1, 1);

        Set<Id> excludedRtIds = new Map<Id, RecordType>([
            SELECT Id
            FROM RecordType
            WHERE SObjectType    = 'sugati__Supplier__c'
            AND   DeveloperName IN ('Agency', 'Agent')
        ]).keySet();

        List<sugati__Supplier_Booking__c> bookings = [
            SELECT Id,
                sugati__SB_Opportunity__c,
                sugati__SB_Opportunity__r.Name,
                sugati__SB_Opportunity__r.AccountId,
                sugati__SB_Opportunity__r.Account.Name,
                sugati__SB_Opportunity__r.sugati__O_Booking_Date__c,
                sugati__S_SB_Total_Gross_Cost_Booking_Currency__c,
                sugati__SB_Night__c,
                sugati__SB_Pax_for_Costing__c,
                sugati__S_SB_Option_Number__c,
                sugati__SB_Room_Type__c,
                sugati__SB_From_Date__c,
                sugati__SB_To_Date__c,
                sugati__SB_Selected_Room_Type__c,
                sugati__SB_Selected_Room_Type__r.Name,
                sugati__SB_Selected_Room_Type__r.sugati__RT_Name__c,
                CurrencyIsoCode
            FROM sugati__Supplier_Booking__c
            WHERE sugati__SB_Supplier__c      =  :supplierId
            AND   sugati__SB_Opportunity__c   != null
            AND   sugati__SB_From_Date__c     >= :windowStart
            AND   sugati__SB_Supplier__r.RecordTypeId NOT IN :excludedRtIds
            ORDER BY sugati__SB_From_Date__c DESC NULLS LAST
            LIMIT 2000
        ];

        // ── DEBUG ─────────────────────────────────────────────────────────────────
        for (sugati__Supplier_Booking__c booking : bookings) {
            Decimal grossCost = booking.sugati__S_SB_Total_Gross_Cost_Booking_Currency__c;
            System.debug('Booking Id: ' + booking.Id);
            System.debug('GrossCost raw value: ' + grossCost);
            System.debug('GrossCost type: Decimal (always in Apex)');
            System.debug('GrossCost setScale(2): ' + (grossCost != null ? String.valueOf(grossCost.setScale(2)) : 'NULL'));
            System.debug('GrossCost JSON: ' + JSON.serialize(grossCost));
        }
        System.debug('Total bookings returned: ' + bookings.size());
        // ── END DEBUG ─────────────────────────────────────────────────────────────

        return bookings;
    }

    /**
     * Retrieves Supplier Contact records linked to a given supplier
     * for display in the Key Contacts component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  supplierId : Id of the Supplier record whose contacts to retrieve
     * @return            : List of sugati__Supplier_Contact__c records ordered by last name ascending
     */
    @AuraEnabled(cacheable=true)
    public static List<sugati__Supplier_Contact__c> getSupplierContacts(Id supplierId) {
        // if (!Utility.canAccessObj('sugati__Supplier_Contact__c')) {
        //     throw new AuraHandledException('Insufficient access to Supplier Contact records.');
        // }
        return [
            SELECT Id,
                   sugati__SC_First_Name__c,
                   sugati__SC_Last_Name__c,
                   sugati__SC_Title__c,
                   sugati__SC_Phone__c,
                   sugati__SC_Email__c,
                   sugati__SC_Language__c
            FROM sugati__Supplier_Contact__c
            WHERE sugati__SC_Supplier__c = :supplierId
            ORDER BY sugati__SC_Last_Name__c ASC
            LIMIT 1000
        ];
    }

    /**
     * Retrieves FAM Visit records linked to a given supplier
     * for display in the Supplier Visits and FAM Trips component.
     * Throws an AuraHandledException if the running user lacks read access to the object.
     * @param  supplierId : Id of the Supplier record whose FAM visits to retrieve
     * @return            : List of sugati__FAM_Visit__c records ordered by start date descending
     */
    @AuraEnabled(cacheable=true)
    public static List<sugati__FAM_Visit__c> getFamVisits(Id supplierId) {
        // if (!Utility.canAccessObj('sugati__FAM_Visit__c')) {
        //     throw new AuraHandledException('Insufficient access to FAM Visit records.');
        // }
        return [
            SELECT Id,
                   sugati__FV_FAM_Visit_Start_Date__c,
                   sugati__FV_FAM_Visit_End_Date__c,
                   sugati__FV_Type_of_FAM__c,
                   sugati__FV_Consultant__c,
                   sugati__FV_Consultant__r.Name,
                   sugati__FV_Description__c
            FROM sugati__FAM_Visit__c
            WHERE sugati__FV_Supplier__c = :supplierId
            ORDER BY sugati__FV_FAM_Visit_Start_Date__c DESC NULLS LAST
            LIMIT 1000
        ];
    }

    /**
     * Returns all-time lifetime aggregates for the Lifetime card on the revenue metrics
     * strip and the LT tab on the annual revenue chart.
     * Uses two aggregate queries — one for the rollup total, one grouped by year.
     * Zero raw rows transferred.
     * @param supplierId : Id of the Supplier record
     * @return           : LifetimeStatsWrapper with totals and per-year breakdown
     */
    @AuraEnabled(cacheable=true)
    public static LifetimeStatsWrapper getLifetimeStats(Id supplierId) {
        try {
            LifetimeStatsWrapper stats = new LifetimeStatsWrapper();
            stats.totalRevenue     = 0;
            stats.totalBookings    = 0;
            stats.firstBookingYear = Date.today().year();
            stats.currencyIsoCode  = 'GBP';
            stats.revenueByYear    = new List<YearlyRevenueItem>();

            // Query 1 — rollup totals
            List<AggregateResult> totals = [
                SELECT SUM(sugati__S_SB_Total_Gross_Cost_Booking_Currency__c) totalRevenue,
                    COUNT(Id)                                              totalBookings,
                    MAX(CurrencyIsoCode)                                   currencyIsoCode
                FROM sugati__Supplier_Booking__c
                WHERE sugati__SB_Supplier__c  = :supplierId
                AND   sugati__SB_Opportunity__c != null
                AND   sugati__SB_Opportunity__r.sugati__O_Booking_Date__c != null
            ];

            if (!totals.isEmpty()) {
                AggregateResult r     = totals[0];
                Object rawRevenue = r.get('totalRevenue');
                stats.totalRevenue = rawRevenue != null 
                    ? ((Decimal) rawRevenue).setScale(2) 
                    : 0;
                stats.totalBookings   = (Integer) r.get('totalBookings')   ?? 0;
                stats.currencyIsoCode = (String)  r.get('currencyIsoCode') ?? 'GBP';
            }

            // Query 2 — revenue grouped by booking year for the LT YOY chart
            // Integer minYear = Date.today().year();
            Integer minYear = null; 
            for (AggregateResult r : [
                SELECT CALENDAR_YEAR(sugati__SB_Opportunity__r.sugati__O_Booking_Date__c) bookingYear,
                    SUM(sugati__S_SB_Total_Gross_Cost_Booking_Currency__c)             revenue
                FROM sugati__Supplier_Booking__c
                WHERE sugati__SB_Supplier__c  = :supplierId
                AND   sugati__SB_Opportunity__c != null
                AND   sugati__SB_Opportunity__r.sugati__O_Booking_Date__c != null
                GROUP BY CALENDAR_YEAR(sugati__SB_Opportunity__r.sugati__O_Booking_Date__c)
                ORDER BY CALENDAR_YEAR(sugati__SB_Opportunity__r.sugati__O_Booking_Date__c) ASC
            ]) {
                Integer yr  = (Integer) r.get('bookingYear');
                Object rawRev = r.get('revenue');
                Decimal rev   = rawRev != null 
                    ? ((Decimal) rawRev).setScale(2) 
                    : 0;

                YearlyRevenueItem item = new YearlyRevenueItem();
                item.year    = yr;
                item.revenue = rev;
                stats.revenueByYear.add(item);

                if (minYear == null || yr < minYear) {
                    minYear = yr;
                }
            }

            stats.firstBookingYear = minYear != null ? minYear : Date.today().year();
            return stats;

        } catch (AuraHandledException ahe) {
            throw ahe;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // ---- INNER CLASSES ----

    public class LifetimeStatsWrapper {
        @AuraEnabled public Decimal totalRevenue     { get; set; }
        @AuraEnabled public Integer totalBookings    { get; set; }
        @AuraEnabled public Integer firstBookingYear { get; set; }
        @AuraEnabled public String  currencyIsoCode  { get; set; }
        @AuraEnabled public List<YearlyRevenueItem> revenueByYear { get; set; }
    }

    public class YearlyRevenueItem {
        @AuraEnabled public Integer year    { get; set; }
        @AuraEnabled public Decimal revenue { get; set; }
    }
}